# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - trial-azure-pipelines

pool: Default

steps:
- powershell: |
    Write-Host printenv
    Get-ChildItem Env:
    Write-Host pwd
    Get-Location
    Write-Host ll
    ls
  displayName: 'Get Environment Variables'
- powershell: |
    Write-Host "Building mod..."
    .\scripts\build_azure.ps1 -mod 'RisingTides' -srcDirectory $Env:BUILD_SOURCESDIRECTORY
  displayName: 'Build Mod Project'
- task: PublishPipelineArtifact@0
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: RisingTides.zip