# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

container: 
  image: aleosiss/xcom2sdk:1.0.1
  endpoint: aleosiss/xcom2sdk

steps:
- powershell: |
    Write-Host printenv
    Get-ChildItem Env:
    Write-Host pwd
    Get-Location
    Write-Host ll
    Get-ChildItem | Sort-Object
  displayName: 'Get Environment Variables'
